/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot
import (
	"time"
)
// ArduinoDevicev2SimpleProperties ArduinoDevicev2SimpleProperties media type (default view)
type ArduinoDevicev2SimpleProperties struct {
	// The name of the property
	Name string `json:"name"`
	// Update date of the property
	UpdatedAt time.Time `json:"updated_at"`
	// Value of the property
	Value interface{} `json:"value"`
}
