/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot
import (
	"time"
)

// ArduinoThing media type (default view)
type ArduinoThing struct {
	// Creation date of the thing
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Delete date of the thing
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// The arn of the device
	DeviceId string `json:"device_id,omitempty"`
	// The api reference of this thing
	Href string `json:"href"`
	// The id of the thing
	Id string `json:"id"`
	// The friendly name of the thing
	Name string `json:"name"`
	// ArduinoPropertyCollection is the media type for an array of ArduinoProperty (default view)
	Properties []ArduinoProperty `json:"properties,omitempty"`
	// The number of properties of the thing
	PropertiesCount float64 `json:"properties_count,omitempty"`
	// The id of the attached sketch
	SketchId string `json:"sketch_id,omitempty"`
	// Update date of the thing
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The user id of the owner
	UserId string `json:"user_id"`
	// Webhook uri
	WebhookActive bool `json:"webhook_active,omitempty"`
	// Webhook uri
	WebhookUri string `json:"webhook_uri,omitempty"`
}
