/*
 * Arduino IoT Cloud API
 *
 *  Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot
import (
	"time"
)
// ArduinoThing ArduinoThing media type (default view)
type ArduinoThing struct {
	// Creation date of the thing
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Delete date of the thing
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// The fqbn of the attached device, if any
	DeviceFqbn string `json:"device_fqbn,omitempty"`
	// The id of the device
	DeviceId string `json:"device_id,omitempty"`
	// The name of the attached device, if any
	DeviceName string `json:"device_name,omitempty"`
	// The type of the attached device, if any
	DeviceType string `json:"device_type,omitempty"`
	// The api reference of this thing
	Href string `json:"href"`
	// The id of the thing
	Id string `json:"id"`
	// The friendly name of the thing
	Name string `json:"name"`
	// ArduinoPropertyCollection is the media type for an array of ArduinoProperty (default view)
	Properties []ArduinoProperty `json:"properties,omitempty"`
	// The number of properties of the thing
	PropertiesCount int64 `json:"properties_count,omitempty"`
	// The id of the attached sketch
	SketchId string `json:"sketch_id,omitempty"`
	// Tags of the thing
	Tags map[string]interface{} `json:"tags,omitempty"`
	// Time zone of the thing
	Timezone string `json:"timezone"`
	// Update date of the thing
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The user id of the owner
	UserId string `json:"user_id"`
	// Webhook uri
	WebhookActive bool `json:"webhook_active,omitempty"`
	// Webhook uri
	WebhookUri string `json:"webhook_uri,omitempty"`
}
