/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

type CreateLoraDevicesV1Payload struct {
	// The app name
	App string `json:"app"`
	// The app eui of the lora device
	AppEui string `json:"app_eui,omitempty"`
	// The app key of the lora device
	AppKey string `json:"app_key,omitempty"`
	// The eui of the lora device
	Eui string `json:"eui"`
	// A common name for the device
	Name string `json:"name"`
	// The optional serial number
	Serial string `json:"serial,omitempty"`
	// The type of device
	Type string `json:"type"`
	// The id of the user. Can be the special string 'me'
	UserId string `json:"user_id"`
}
