/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

// ArduinoLoradevicev1 media type (default view)
type ArduinoLoradevicev1 struct {
	// The eui of the app
	AppEui string `json:"app_eui"`
	// The key of the device
	AppKey string `json:"app_key"`
	// The id of the device
	DeviceId string `json:"device_id"`
	// The eui of the lora device
	Eui string `json:"eui"`
}
