/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot
import (
	"time"
)

type CreateDevicesV2PubkeysPayload struct {
	// Whether the public key is enabled
	Enabled bool `json:"enabled"`
	// When the public key will expire
	Expire time.Time `json:"expire"`
	// The public key in pem format
	Pem string `json:"pem"`
}
