/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

type Devicev2Webhook struct {
	// Whether the webhook is active
	Active bool `json:"active,omitempty"`
	// The uri of the webhook
	Uri string `json:"uri"`
}
