/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

type CheckDevicesV2PassPayload struct {
	// The password for the device
	Password string `json:"password"`
}
