/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

// ArduinoDashboardlist media type (default view)
type ArduinoDashboardlist struct {
	// The dashboards of the users
	Dashboards []ArduinoDashboard `json:"dashboards"`
}
