/*
 * Iot API
 *
 * Collection of all public API endpoints.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iot

// ClientPayload describes an oauth client
type Client struct {
	// The name of the client
	Name string `json:"name"`
}
